project:
  type: website
  output-dir: "docs"
website:
  title: "Janette Phan"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Assignments"
        menu:
          - assignment01.qmd
          - assignment02.qmd
          - assignment03.qmd
          - assignment04.qmd
      - text: "Reviews"
        file: reviews.qmd
      - text: "CV/Resume"
        file: Resume.qmd

    right:
      - icon: github
        href: https://github.com/phanjanette
      - icon: linkedIn
        href: https://www.linkedin.com/in/janettephan04/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: visual

